In [9]:
import pandas as pd
import ast
import numpy as np
import re
from collections import Counter
import matplotlib.pyplot as plt
import matplotlib
import string 
import functions

### data proprcessing & statistic

In [3]:
# read the data
data = pd.read_csv("/Users/sunwen/Desktop/dataset/dataset_new/final_data.csv")

- extract the recipe id and the numerical value of calorie and preparation time from orginal dataset

In [4]:
# extract the recipe id from recipe urls
list_cat_no = []
i = 0
for item in data['recipe_url']:
    list_cat_no.append(item.split('/')[4])
    
# add one column "recipe_id" into the dataset and set it as the index of dataset
data['recipe_id'] = list_cat_no
data = data.set_index(["recipe_id"])

# extract the numerical value string in the column calorie 
pat = r"([-+]?\d*\.\d+|\d+)"
data["calorie_value"] = data["calorie"].str.extract(pat, flags=0, expand=True)
data["preparation_time_value"] = data["preparation_time"].str.extract(pat, flags=0, expand=True)

In [6]:
data.head()

,categorize,recipe_name,tags,avg_score,difficulty,ingredient,rating_count,calorie,preparation_time,comment_user,recipe_url,calorie_value,preparation_time_value
recipe_id,,,,,,,,,,,,,
2369421376028274,Menüart,"""A bis Z""-Salat","['Salat', 'Gemüse', 'Sommer', 'Vegetarisch', '...",2.67,simpel,"['1m.-große', 'Zucchini', '1', 'Apfel,säuerlic...",1.0,NaN,15 Min,"[{'rating': 'rating-3', 'comment_time': '24.09...",https://www.chefkoch.de/rezepte/23694213760282...,NaN,15.0
1883831306402031,Menüart,"""Aufgehende Sonne""","['Asien', 'Hauptspeise', 'Nudeln', 'Beilage', ...",3.60,normal,"['500g', 'Nudeln(Mie-),ReisnudelnoderReis', '4...",3.0,500kcal,30 Min,"[{'rating': 'rating-5', 'comment_time': '10.08...",https://www.chefkoch.de/rezepte/18838313064020...,500.0,30.0
3615831543679585,Regional,"""Black and White"" New York Cheesecake","['Backen', 'USAoderKanada', 'Kuchen']",0.00,normal,"['250g', 'Bitterschokolade,70%', '300g', 'Schl...",0.0,NaN,60 Min,NaN,https://www.chefkoch.de/rezepte/36158315436795...,NaN,60.0
2256081360958630,Getränke,"""Bloody Berry"" Halloween Smoothie","['Getränk', 'Halloween', 'Party', 'Kinder', 'S...",3.25,simpel,"['250g', 'Beeren(Beeren-Mix,TK)', '250ml', 'Na...",2.0,NaN,5 Min,"[{'rating': 'rating-4', 'comment_time': '31.10...",https://www.chefkoch.de/rezepte/22560813609586...,NaN,5.0
3387501504018214,Menüart,"""Bottermelk Anballerste""","['Hauptspeise', 'Europa', 'Suppe', 'gebunden',...",3.60,normal,"['500g', 'Kartoffel(n)', '1', 'Zwiebel(n)', '1...",3.0,NaN,15 Min,"[{'rating': 'rating-3', 'comment_time': '10.11...",https://www.chefkoch.de/rezepte/33875015040182...,NaN,15.0

- Basic description of dataset

In [5]:
data_info = data
data_info["calorie_value"] = data_info["calorie_value"].astype(float)
data_info["preparation_time_value"] = data_info["preparation_time_value"].astype(float)
data_info.describe()

           avg_score   rating_count  calorie_value  preparation_time_value
count  104986.000000  104986.000000   22651.000000           104986.000000
mean        2.492965       7.203302     830.093638               24.489608
std         1.640829      31.406500    1343.459930               28.735487
min         0.000000       0.000000       1.000000                1.000000
25%         0.000000       0.000000     269.000000               15.000000
50%         3.250000       1.000000     442.000000               20.000000
75%         3.710000       4.000000     710.000000               30.000000
max         4.860000     995.000000   65535.000000             4200.000000

- extract the user information from original dataset to create a new dataset

In [7]:
# drop all rows with nan value in both columns comment_user and calorie_value
data_com = data.dropna(subset=["comment_user",'calorie_value'])
len(data_com)

19536

In [ ]:
# expand the corresponding recipe data for each comment user
df_com_1 = functions.extract_com_user(data_com)
df_com_2 = functions.sub_cat_in_com(data_com)
df_com_3 = functions.add_recipe_info(data_com)
df_com_new = df_com_1.merge(df_com_2, on='recipe_id', how='left')
df_com_new = df_com_new.merge(df_com_3, on='recipe_id', how='left')

#df_com_new = df_com_new[['recipe_id','recipe_name','tags','difficulty','preparation_time','ingredient','name','rating','sex','age','marriage_status','comment_time','calorie_value']]
df_com_new = df_com_new.set_index(["recipe_id"])

In [ ]:
df_com_new.head()